# Data Reading

In [1]:
from pyspark.sql.functions import *
from pyspark.sql.types import *
from pyspark.sql.window import Window

In [2]:
df = spark.read.format("delta")\
    .load("s3://learn-databricks-project-e2e-1-bronze/orders")
display(df)

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

DataFrame[order_id: string, customer_id: string, product_id: string, order_date: date, quantity: int, total_amount: double, _rescued_data: string]

In [3]:
df.printSchema()

root
 |-- order_id: string (nullable = true)
 |-- customer_id: string (nullable = true)
 |-- product_id: string (nullable = true)
 |-- order_date: date (nullable = true)
 |-- quantity: integer (nullable = true)
 |-- total_amount: double (nullable = true)
 |-- _rescued_data: string (nullable = true)

In [4]:
df = df.withColumnRenamed("_rescued_data", "rescued_data")

In [5]:
df = df.drop("rescued_data")
display(df)

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

DataFrame[order_id: string, customer_id: string, product_id: string, order_date: date, quantity: int, total_amount: double]

In [6]:
df = df.withColumn("order_date", to_timestamp(col("order_date")))
df.show()

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

+--------+-----------+----------+-------------------+--------+------------+
|order_id|customer_id|product_id|         order_date|quantity|total_amount|
+--------+-----------+----------+-------------------+--------+------------+
|  O00001|     C00710|     P0159|2023-03-22 00:00:00|       3|     2022.87|
|  O00002|     C00954|     P0036|2023-06-30 00:00:00|       2|     3560.74|
|  O00003|     C01578|     P0427|2023-11-06 00:00:00|       3|     5903.52|
|  O00004|     C00962|     P0332|2024-02-27 00:00:00|       3|     4107.99|
|  O00005|     C00156|     P0038|2024-10-13 00:00:00|       5|     5784.95|
|  O00006|     C00521|     P0174|2023-05-17 00:00:00|       5|      407.75|
|  O00007|     C00982|     P0352|2024-01-18 00:00:00|       4|     4907.64|
|  O00008|     C00976|     P0172|2023-01-10 00:00:00|       4|     7037.88|
|  O00009|     C01001|     P0238|2023-04-20 00:00:00|       3|     4076.97|
|  O00010|     C00702|     P0258|2023-07-07 00:00:00|       4|     5695.64|
|  O00011|     C01447|     P0068|2023-03-02 00:00:00|       1|     1633.64|
|  O00012|     C01167|     P0085|2024-05-02 00:00:00|       4|     7452.32|
|  O00013|     C00505|     P0158|2024-08-05 00:00:00|       1|      1286.8|
|  O00014|     C01972|     P0348|2023-04-10 00:00:00|       1|      958.75|
|  O00015|     C01571|     P0132|2023-09-12 00:00:00|       2|     2388.44|
|  O00016|     C00830|     P0079|2024-08-07 00:00:00|       5|     3902.25|
|  O00017|     C00577|     P0381|2024-09-25 00:00:00|       1|     1203.96|
|  O00018|     C00522|     P0430|2023-02-17 00:00:00|       5|      6931.6|
|  O00019|     C01291|     P0434|2024-12-14 00:00:00|       1|     1689.45|
|  O00020|     C01835|     P0027|2024-03-05 00:00:00|       5|      4699.5|
+--------+-----------+----------+-------------------+--------+------------+
only showing top 20 rows

In [7]:
df = df.withColumn("year", year(col("order_date")))\
    .withColumn("month", month(col("order_date")))\
    .withColumn("day", dayofmonth(col("order_date")))
    
df.show()

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

+--------+-----------+----------+-------------------+--------+------------+----+-----+---+
|order_id|customer_id|product_id|         order_date|quantity|total_amount|year|month|day|
+--------+-----------+----------+-------------------+--------+------------+----+-----+---+
|  O00001|     C00710|     P0159|2023-03-22 00:00:00|       3|     2022.87|2023|    3| 22|
|  O00002|     C00954|     P0036|2023-06-30 00:00:00|       2|     3560.74|2023|    6| 30|
|  O00003|     C01578|     P0427|2023-11-06 00:00:00|       3|     5903.52|2023|   11|  6|
|  O00004|     C00962|     P0332|2024-02-27 00:00:00|       3|     4107.99|2024|    2| 27|
|  O00005|     C00156|     P0038|2024-10-13 00:00:00|       5|     5784.95|2024|   10| 13|
|  O00006|     C00521|     P0174|2023-05-17 00:00:00|       5|      407.75|2023|    5| 17|
|  O00007|     C00982|     P0352|2024-01-18 00:00:00|       4|     4907.64|2024|    1| 18|
|  O00008|     C00976|     P0172|2023-01-10 00:00:00|       4|     7037.88|2023|    1| 10|
|  O00009|     C01001|     P0238|2023-04-20 00:00:00|       3|     4076.97|2023|    4| 20|
|  O00010|     C00702|     P0258|2023-07-07 00:00:00|       4|     5695.64|2023|    7|  7|
|  O00011|     C01447|     P0068|2023-03-02 00:00:00|       1|     1633.64|2023|    3|  2|
|  O00012|     C01167|     P0085|2024-05-02 00:00:00|       4|     7452.32|2024|    5|  2|
|  O00013|     C00505|     P0158|2024-08-05 00:00:00|       1|      1286.8|2024|    8|  5|
|  O00014|     C01972|     P0348|2023-04-10 00:00:00|       1|      958.75|2023|    4| 10|
|  O00015|     C01571|     P0132|2023-09-12 00:00:00|       2|     2388.44|2023|    9| 12|
|  O00016|     C00830|     P0079|2024-08-07 00:00:00|       5|     3902.25|2024|    8|  7|
|  O00017|     C00577|     P0381|2024-09-25 00:00:00|       1|     1203.96|2024|    9| 25|
|  O00018|     C00522|     P0430|2023-02-17 00:00:00|       5|      6931.6|2023|    2| 17|
|  O00019|     C01291|     P0434|2024-12-14 00:00:00|       1|     1689.45|2024|   12| 14|
|  O00020|     C01835|     P0027|2024-03-05 00:00:00|       5|      4699.5|2024|    3|  5|
+--------+-----------+----------+-------------------+--------+------------+----+-----+---+
only showing top 20 rows

In [8]:
df1 = df.withColumn("flag",dense_rank().over(Window.partitionBy("year").orderBy(desc("total_amount"))))
df1.show()

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

+--------+-----------+----------+-------------------+--------+------------+----+-----+---+----+
|order_id|customer_id|product_id|         order_date|quantity|total_amount|year|month|day|flag|
+--------+-----------+----------+-------------------+--------+------------+----+-----+---+----+
|  O00957|     C01449|     P0498|2023-10-05 00:00:00|       5|      9952.9|2023|   10|  5|   1|
|  O01765|     C01515|     P0498|2023-05-11 00:00:00|       5|      9952.9|2023|    5| 11|   1|
|  O03502|     C00805|     P0498|2023-09-24 00:00:00|       5|      9952.9|2023|    9| 24|   1|
|  O03660|     C01001|     P0498|2023-10-08 00:00:00|       5|      9952.9|2023|   10|  8|   1|
|  O06790|     C01819|     P0498|2023-02-27 00:00:00|       5|      9952.9|2023|    2| 27|   1|
|  O03989|     C00631|     P0440|2023-11-20 00:00:00|       5|     9916.25|2023|   11| 20|   2|
|  O07763|     C00471|     P0440|2023-04-12 00:00:00|       5|     9916.25|2023|    4| 12|   2|
|  O03272|     C01879|     P0165|2023-02-15 00:00:00|       5|     9858.85|2023|    2| 15|   3|
|  O03746|     C01713|     P0165|2023-10-26 00:00:00|       5|     9858.85|2023|   10| 26|   3|
|  O08261|     C00988|     P0165|2023-11-29 00:00:00|       5|     9858.85|2023|   11| 29|   3|
|  O00412|     C00748|     P0427|2023-03-23 00:00:00|       5|      9839.2|2023|    3| 23|   4|
|  O04478|     C01560|     P0427|2023-10-04 00:00:00|       5|      9839.2|2023|   10|  4|   4|
|  O05528|     C01500|     P0427|2023-02-02 00:00:00|       5|      9839.2|2023|    2|  2|   4|
|  O05611|     C00823|     P0427|2023-08-10 00:00:00|       5|      9839.2|2023|    8| 10|   4|
|  O09576|     C00681|     P0121|2023-07-15 00:00:00|       5|     9796.15|2023|    7| 15|   5|
|  O05466|     C00156|     P0252|2023-03-08 00:00:00|       5|      9786.9|2023|    3|  8|   6|
|  O05537|     C00615|     P0252|2023-01-12 00:00:00|       5|      9786.9|2023|    1| 12|   6|
|  O00710|     C00293|     P0369|2023-09-05 00:00:00|       5|     9773.85|2023|    9|  5|   7|
|  O03801|     C00557|     P0202|2023-01-09 00:00:00|       5|     9769.95|2023|    1|  9|   8|
|  O01755|     C00341|     P0179|2023-08-22 00:00:00|       5|      9750.2|2023|    8| 22|   9|
+--------+-----------+----------+-------------------+--------+------------+----+-----+---+----+
only showing top 20 rows

In [9]:
df2 = df1.withColumn("rank_flag", rank().over(Window.partitionBy("year").orderBy(desc("total_amount"))))
df2.show()

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

+--------+-----------+----------+-------------------+--------+------------+----+-----+---+----+---------+
|order_id|customer_id|product_id|         order_date|quantity|total_amount|year|month|day|flag|rank_flag|
+--------+-----------+----------+-------------------+--------+------------+----+-----+---+----+---------+
|  O00957|     C01449|     P0498|2023-10-05 00:00:00|       5|      9952.9|2023|   10|  5|   1|        1|
|  O01765|     C01515|     P0498|2023-05-11 00:00:00|       5|      9952.9|2023|    5| 11|   1|        1|
|  O03502|     C00805|     P0498|2023-09-24 00:00:00|       5|      9952.9|2023|    9| 24|   1|        1|
|  O03660|     C01001|     P0498|2023-10-08 00:00:00|       5|      9952.9|2023|   10|  8|   1|        1|
|  O06790|     C01819|     P0498|2023-02-27 00:00:00|       5|      9952.9|2023|    2| 27|   1|        1|
|  O03989|     C00631|     P0440|2023-11-20 00:00:00|       5|     9916.25|2023|   11| 20|   2|        6|
|  O07763|     C00471|     P0440|2023-04-12 00:00:00|       5|     9916.25|2023|    4| 12|   2|        6|
|  O03272|     C01879|     P0165|2023-02-15 00:00:00|       5|     9858.85|2023|    2| 15|   3|        8|
|  O03746|     C01713|     P0165|2023-10-26 00:00:00|       5|     9858.85|2023|   10| 26|   3|        8|
|  O08261|     C00988|     P0165|2023-11-29 00:00:00|       5|     9858.85|2023|   11| 29|   3|        8|
|  O00412|     C00748|     P0427|2023-03-23 00:00:00|       5|      9839.2|2023|    3| 23|   4|       11|
|  O04478|     C01560|     P0427|2023-10-04 00:00:00|       5|      9839.2|2023|   10|  4|   4|       11|
|  O05528|     C01500|     P0427|2023-02-02 00:00:00|       5|      9839.2|2023|    2|  2|   4|       11|
|  O05611|     C00823|     P0427|2023-08-10 00:00:00|       5|      9839.2|2023|    8| 10|   4|       11|
|  O09576|     C00681|     P0121|2023-07-15 00:00:00|       5|     9796.15|2023|    7| 15|   5|       15|
|  O05466|     C00156|     P0252|2023-03-08 00:00:00|       5|      9786.9|2023|    3|  8|   6|       16|
|  O05537|     C00615|     P0252|2023-01-12 00:00:00|       5|      9786.9|2023|    1| 12|   6|       16|
|  O00710|     C00293|     P0369|2023-09-05 00:00:00|       5|     9773.85|2023|    9|  5|   7|       18|
|  O03801|     C00557|     P0202|2023-01-09 00:00:00|       5|     9769.95|2023|    1|  9|   8|       19|
|  O01755|     C00341|     P0179|2023-08-22 00:00:00|       5|      9750.2|2023|    8| 22|   9|       20|
+--------+-----------+----------+-------------------+--------+------------+----+-----+---+----+---------+
only showing top 20 rows

In [10]:
df3 = df2.withColumn("row_flag", row_number().over(Window.partitionBy("year").orderBy(desc("total_amount"))))
df3.show()

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

+--------+-----------+----------+-------------------+--------+------------+----+-----+---+----+---------+--------+
|order_id|customer_id|product_id|         order_date|quantity|total_amount|year|month|day|flag|rank_flag|row_flag|
+--------+-----------+----------+-------------------+--------+------------+----+-----+---+----+---------+--------+
|  O00957|     C01449|     P0498|2023-10-05 00:00:00|       5|      9952.9|2023|   10|  5|   1|        1|       1|
|  O01765|     C01515|     P0498|2023-05-11 00:00:00|       5|      9952.9|2023|    5| 11|   1|        1|       2|
|  O03502|     C00805|     P0498|2023-09-24 00:00:00|       5|      9952.9|2023|    9| 24|   1|        1|       3|
|  O03660|     C01001|     P0498|2023-10-08 00:00:00|       5|      9952.9|2023|   10|  8|   1|        1|       4|
|  O06790|     C01819|     P0498|2023-02-27 00:00:00|       5|      9952.9|2023|    2| 27|   1|        1|       5|
|  O03989|     C00631|     P0440|2023-11-20 00:00:00|       5|     9916.25|2023|   11| 20|   2|        6|       6|
|  O07763|     C00471|     P0440|2023-04-12 00:00:00|       5|     9916.25|2023|    4| 12|   2|        6|       7|
|  O03272|     C01879|     P0165|2023-02-15 00:00:00|       5|     9858.85|2023|    2| 15|   3|        8|       8|
|  O03746|     C01713|     P0165|2023-10-26 00:00:00|       5|     9858.85|2023|   10| 26|   3|        8|       9|
|  O08261|     C00988|     P0165|2023-11-29 00:00:00|       5|     9858.85|2023|   11| 29|   3|        8|      10|
|  O00412|     C00748|     P0427|2023-03-23 00:00:00|       5|      9839.2|2023|    3| 23|   4|       11|      11|
|  O04478|     C01560|     P0427|2023-10-04 00:00:00|       5|      9839.2|2023|   10|  4|   4|       11|      12|
|  O05528|     C01500|     P0427|2023-02-02 00:00:00|       5|      9839.2|2023|    2|  2|   4|       11|      13|
|  O05611|     C00823|     P0427|2023-08-10 00:00:00|       5|      9839.2|2023|    8| 10|   4|       11|      14|
|  O09576|     C00681|     P0121|2023-07-15 00:00:00|       5|     9796.15|2023|    7| 15|   5|       15|      15|
|  O05466|     C00156|     P0252|2023-03-08 00:00:00|       5|      9786.9|2023|    3|  8|   6|       16|      16|
|  O05537|     C00615|     P0252|2023-01-12 00:00:00|       5|      9786.9|2023|    1| 12|   6|       16|      17|
|  O00710|     C00293|     P0369|2023-09-05 00:00:00|       5|     9773.85|2023|    9|  5|   7|       18|      18|
|  O03801|     C00557|     P0202|2023-01-09 00:00:00|       5|     9769.95|2023|    1|  9|   8|       19|      19|
|  O01755|     C00341|     P0179|2023-08-22 00:00:00|       5|      9750.2|2023|    8| 22|   9|       20|      20|
+--------+-----------+----------+-------------------+--------+------------+----+-----+---+----+---------+--------+
only showing top 20 rows

# Classes - OOP

In [11]:
class windows:
       
    def dense_rank(self, df):
        df_dense_rank = df.withColumn("dense_rank_flag", dense_rank().over(Window.partitionBy("year").orderBy(desc("total_amount"))))
        return df_dense_rank
    
    def rank(self, df):
        df_rank = df.withColumn("rank_flag", rank().over(Window.partitionBy("year").orderBy(desc("total_amount"))))
        return df_rank
    
    def row_number(self, df):
        df_row_number = df.withColumn("row_flag", row_number().over(Window.partitionBy("year").orderBy(desc("total_amount"))))
        return df_row_number

In [12]:
obj = windows()

In [13]:
df_result = obj.dense_rank(df)
df_result.show()

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

+--------+-----------+----------+-------------------+--------+------------+----+-----+---+---------------+
|order_id|customer_id|product_id|         order_date|quantity|total_amount|year|month|day|dense_rank_flag|
+--------+-----------+----------+-------------------+--------+------------+----+-----+---+---------------+
|  O00957|     C01449|     P0498|2023-10-05 00:00:00|       5|      9952.9|2023|   10|  5|              1|
|  O01765|     C01515|     P0498|2023-05-11 00:00:00|       5|      9952.9|2023|    5| 11|              1|
|  O03502|     C00805|     P0498|2023-09-24 00:00:00|       5|      9952.9|2023|    9| 24|              1|
|  O03660|     C01001|     P0498|2023-10-08 00:00:00|       5|      9952.9|2023|   10|  8|              1|
|  O06790|     C01819|     P0498|2023-02-27 00:00:00|       5|      9952.9|2023|    2| 27|              1|
|  O03989|     C00631|     P0440|2023-11-20 00:00:00|       5|     9916.25|2023|   11| 20|              2|
|  O07763|     C00471|     P0440|2023-04-12 00:00:00|       5|     9916.25|2023|    4| 12|              2|
|  O03272|     C01879|     P0165|2023-02-15 00:00:00|       5|     9858.85|2023|    2| 15|              3|
|  O03746|     C01713|     P0165|2023-10-26 00:00:00|       5|     9858.85|2023|   10| 26|              3|
|  O08261|     C00988|     P0165|2023-11-29 00:00:00|       5|     9858.85|2023|   11| 29|              3|
|  O00412|     C00748|     P0427|2023-03-23 00:00:00|       5|      9839.2|2023|    3| 23|              4|
|  O04478|     C01560|     P0427|2023-10-04 00:00:00|       5|      9839.2|2023|   10|  4|              4|
|  O05528|     C01500|     P0427|2023-02-02 00:00:00|       5|      9839.2|2023|    2|  2|              4|
|  O05611|     C00823|     P0427|2023-08-10 00:00:00|       5|      9839.2|2023|    8| 10|              4|
|  O09576|     C00681|     P0121|2023-07-15 00:00:00|       5|     9796.15|2023|    7| 15|              5|
|  O05466|     C00156|     P0252|2023-03-08 00:00:00|       5|      9786.9|2023|    3|  8|              6|
|  O05537|     C00615|     P0252|2023-01-12 00:00:00|       5|      9786.9|2023|    1| 12|              6|
|  O00710|     C00293|     P0369|2023-09-05 00:00:00|       5|     9773.85|2023|    9|  5|              7|
|  O03801|     C00557|     P0202|2023-01-09 00:00:00|       5|     9769.95|2023|    1|  9|              8|
|  O01755|     C00341|     P0179|2023-08-22 00:00:00|       5|      9750.2|2023|    8| 22|              9|
+--------+-----------+----------+-------------------+--------+------------+----+-----+---+---------------+
only showing top 20 rows

# Data Writing

In [ ]:
df.write.format("delta")\
    .mode("overwrite")\
    .save("s3://learn-databricks-project-e2e-1-silver/orders")

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

In [15]:
%sql

CREATE TABLE IF NOT EXISTS learn_e2e_1.silver.orders
USING DELTA
LOCATION 's3://learn-databricks-project-e2e-1-silver/orders'

DataFrame[]