In [1]:
from pyspark.sql import Window
from pyspark.sql.functions import *
from pyspark.sql.types import *
import time

# Data Reading

In [2]:
df = spark.read.format("delta")\
    .load("s3://learn-databricks-project-e2e-1-bronze/products")
    
df.show()

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

+----------+-----------------+-----------+-------+-------+-------------+
|product_id|     product_name|   category|  brand|  price|_rescued_data|
+----------+-----------------+-----------+-------+-------+-------------+
|     P0001|      Clearly Its|     Beauty|   Nike|1868.54|         NULL|
|     P0002| Production Clear|     Beauty|  Apple| 587.13|         NULL|
|     P0003|    Culture Coach|       Home| Revlon|1599.24|         NULL|
|     P0004|    Movement Part|     Sports|     LG| 651.71|         NULL|
|     P0005|        Fact Name|   Clothing|Samsung|1861.78|         NULL|
|     P0006|     Usually Stop|       Toys| Adidas| 936.36|         NULL|
|     P0007|   Reveal Current|     Sports| Adidas|1954.02|         NULL|
|     P0008|   Force Language|     Beauty|   Puma|1251.26|         NULL|
|     P0009|        Stage Leg|   Clothing|Samsung|1247.15|         NULL|
|     P0010|      Leader Then|     Sports|   Sony| 975.53|         NULL|
|     P0011|        Term Rest|Electronics| Adidas|1475.31|         NULL|
|     P0012|     Theory Wrong|Electronics|  Apple| 624.61|         NULL|
|     P0013|    Democrat Book|     Sports|   Puma| 384.99|         NULL|
|     P0014|   Follow Brother|   Clothing|   Dell|   32.2|         NULL|
|     P0015|    Pattern Story|     Beauty|     LG| 1459.2|         NULL|
|     P0016|       Policy Nor|   Clothing|Samsung|1594.08|         NULL|
|     P0017|    After Project|     Beauty| Revlon|1289.06|         NULL|
|     P0018|Technology Chance|     Beauty|   Puma|1329.53|         NULL|
|     P0019|      Oil Station|Electronics|Samsung| 230.56|         NULL|
|     P0020|     Happen Truth|     Beauty|   Nike| 1603.5|         NULL|
+----------+-----------------+-----------+-------+-------+-------------+
only showing top 20 rows

In [3]:
df = df.drop("_rescued_data")
df.show()

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

+----------+-----------------+-----------+-------+-------+
|product_id|     product_name|   category|  brand|  price|
+----------+-----------------+-----------+-------+-------+
|     P0001|      Clearly Its|     Beauty|   Nike|1868.54|
|     P0002| Production Clear|     Beauty|  Apple| 587.13|
|     P0003|    Culture Coach|       Home| Revlon|1599.24|
|     P0004|    Movement Part|     Sports|     LG| 651.71|
|     P0005|        Fact Name|   Clothing|Samsung|1861.78|
|     P0006|     Usually Stop|       Toys| Adidas| 936.36|
|     P0007|   Reveal Current|     Sports| Adidas|1954.02|
|     P0008|   Force Language|     Beauty|   Puma|1251.26|
|     P0009|        Stage Leg|   Clothing|Samsung|1247.15|
|     P0010|      Leader Then|     Sports|   Sony| 975.53|
|     P0011|        Term Rest|Electronics| Adidas|1475.31|
|     P0012|     Theory Wrong|Electronics|  Apple| 624.61|
|     P0013|    Democrat Book|     Sports|   Puma| 384.99|
|     P0014|   Follow Brother|   Clothing|   Dell|   32.2|
|     P0015|    Pattern Story|     Beauty|     LG| 1459.2|
|     P0016|       Policy Nor|   Clothing|Samsung|1594.08|
|     P0017|    After Project|     Beauty| Revlon|1289.06|
|     P0018|Technology Chance|     Beauty|   Puma|1329.53|
|     P0019|      Oil Station|Electronics|Samsung| 230.56|
|     P0020|     Happen Truth|     Beauty|   Nike| 1603.5|
+----------+-----------------+-----------+-------+-------+
only showing top 20 rows

# Functions

In [4]:
df.createOrReplaceTempView("products")

In [5]:
%sql

CREATE OR REPLACE FUNCTION learn_e2e_1.bronze.discount_func(p_price DOUBLE)
RETURNS DOUBLE
LANGUAGE SQL
RETURN p_price * 0.90

DataFrame[]

In [6]:
%sql

SELECT product_id, price, learn_e2e_1.bronze.discount_func(price) AS discounted_price
FROM products

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

DataFrame[product_id: string, price: double, discounted_price: double]

In [7]:
df.withColumn("discounted_price", expr("learn_e2e_1.bronze.discount_func(price)")).show()

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

+----------+-----------------+-----------+-------+-------+------------------+
|product_id|     product_name|   category|  brand|  price|  discounted_price|
+----------+-----------------+-----------+-------+-------+------------------+
|     P0001|      Clearly Its|     Beauty|   Nike|1868.54|          1681.686|
|     P0002| Production Clear|     Beauty|  Apple| 587.13|           528.417|
|     P0003|    Culture Coach|       Home| Revlon|1599.24|          1439.316|
|     P0004|    Movement Part|     Sports|     LG| 651.71| 586.5390000000001|
|     P0005|        Fact Name|   Clothing|Samsung|1861.78|          1675.602|
|     P0006|     Usually Stop|       Toys| Adidas| 936.36|           842.724|
|     P0007|   Reveal Current|     Sports| Adidas|1954.02|          1758.618|
|     P0008|   Force Language|     Beauty|   Puma|1251.26|          1126.134|
|     P0009|        Stage Leg|   Clothing|Samsung|1247.15|1122.4350000000002|
|     P0010|      Leader Then|     Sports|   Sony| 975.53|           877.977|
|     P0011|        Term Rest|Electronics| Adidas|1475.31|          1327.779|
|     P0012|     Theory Wrong|Electronics|  Apple| 624.61|           562.149|
|     P0013|    Democrat Book|     Sports|   Puma| 384.99|346.49100000000004|
|     P0014|   Follow Brother|   Clothing|   Dell|   32.2|28.980000000000004|
|     P0015|    Pattern Story|     Beauty|     LG| 1459.2|           1313.28|
|     P0016|       Policy Nor|   Clothing|Samsung|1594.08|          1434.672|
|     P0017|    After Project|     Beauty| Revlon|1289.06|          1160.154|
|     P0018|Technology Chance|     Beauty|   Puma|1329.53|          1196.577|
|     P0019|      Oil Station|Electronics|Samsung| 230.56|207.50400000000002|
|     P0020|     Happen Truth|     Beauty|   Nike| 1603.5|           1443.15|
+----------+-----------------+-----------+-------+-------+------------------+
only showing top 20 rows

In [8]:
%sql

CREATE OR REPLACE FUNCTION learn_e2e_1.bronze.upper_func(p_brand STRING)
RETURNS STRING
LANGUAGE PYTHON
AS
$$
    return p_brand.upper()
$$

DataFrame[]

In [9]:
%sql
SELECT product_id, brand, learn_e2e_1.bronze.upper_func(brand) AS upper_brand
FROM products

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

DataFrame[product_id: string, brand: string, upper_brand: string]

In [10]:
df.write.format("delta")\
    .mode("overwrite")\
    .option("path", "s3://learn-databricks-project-e2e-1-silver/products")\
    .save()

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

In [11]:
%sql

CREATE TABLE IF NOT EXISTS learn_e2e_1.silver.products
USING DELTA
LOCATION 's3://learn-databricks-project-e2e-1-silver/products'

DataFrame[]