In [2]:
from pyspark.sql.functions import *
from pyspark.sql.types import *
from pyspark.sql.window import Window
import time

# Data Reading

In [3]:
df = spark.read.format("delta")\
    .load("s3://learn-databricks-project-e2e-1-bronze/customers")
    
df.show()

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

+-----------+----------+---------+--------------------+------------------+-----+-------------+
|customer_id|first_name|last_name|               email|              city|state|_rescued_data|
+-----------+----------+---------+--------------------+------------------+-----+-------------+
|     C00001|     Emily|   Mooney|   rushjeff@ryan.org|      Johnsonmouth|   MS|         NULL|
|     C00002|    Andrea|  Sellers|mccoykiara@kelly.com|       Stephenfort|   WY|         NULL|
|     C00003|     Craig|    Hayes|rebeccamiller@yah...|South Stephenshire|   LA|         NULL|
|     C00004|     Bryan|    Scott|lawrence05@campbe...|         Chrisland|   ND|         NULL|
|     C00005|      Sean|  Vasquez|  carrie45@yahoo.com|   East Dennistown|   RI|         NULL|
|     C00006|     Kevin| Mccarthy|traceyramos@gmail...|     North Matthew|   IN|         NULL|
|     C00007|    Amanda|    Doyle|scottallen@gmail.com|        Joneshaven|   VA|         NULL|
|     C00008|      Paul|   Campos|sullivanjeremy@ho...|  South Nathanfurt|   CT|         NULL|
|     C00009|      Mary|    Green|  dennis03@yahoo.com|      Kimberlyview|   MD|         NULL|
|     C00010|     James|    Myers|charles58@murillo...|       West Hector|   OK|         NULL|
|     C00011|     Jacob|       Le|   anita65@gmail.com|       Houstonfurt|   AR|         NULL|
|     C00012|      Chad|    Banks|beardtravis@gmail...| East Jenniferview|   WI|         NULL|
|     C00013|     James|   Martin|     jwood@gmail.com| Lake Gregoryshire|   OR|         NULL|
|     C00014|    Thomas|  Hartman|    lmoore@yahoo.com|  East Tiffanybury|   MS|         NULL|
|     C00015|     Diane|   Harris|daniellowe@hotmai...|    South Courtney|   SC|         NULL|
|     C00016|     Brett|   Parker|  amylam@collins.org|        Jesusburgh|   IA|         NULL|
|     C00017|    Angela|   Carter|rhondaferguson@gm...|  West Loriborough|   GA|         NULL|
|     C00018|   Darrell|    Chang|martinfrank@brook...|  Lake Joshuamouth|   OH|         NULL|
|     C00019|     Angie|     King|russelltimothy@si...|  East Anthonyland|   NY|         NULL|
|     C00020|      Juan|  Collins|rojassandra@hotma...|       South Oscar|   NV|         NULL|
+-----------+----------+---------+--------------------+------------------+-----+-------------+
only showing top 20 rows

In [4]:
df = df.drop("_rescued_data")
df.show()

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

+-----------+----------+---------+--------------------+------------------+-----+
|customer_id|first_name|last_name|               email|              city|state|
+-----------+----------+---------+--------------------+------------------+-----+
|     C00001|     Emily|   Mooney|   rushjeff@ryan.org|      Johnsonmouth|   MS|
|     C00002|    Andrea|  Sellers|mccoykiara@kelly.com|       Stephenfort|   WY|
|     C00003|     Craig|    Hayes|rebeccamiller@yah...|South Stephenshire|   LA|
|     C00004|     Bryan|    Scott|lawrence05@campbe...|         Chrisland|   ND|
|     C00005|      Sean|  Vasquez|  carrie45@yahoo.com|   East Dennistown|   RI|
|     C00006|     Kevin| Mccarthy|traceyramos@gmail...|     North Matthew|   IN|
|     C00007|    Amanda|    Doyle|scottallen@gmail.com|        Joneshaven|   VA|
|     C00008|      Paul|   Campos|sullivanjeremy@ho...|  South Nathanfurt|   CT|
|     C00009|      Mary|    Green|  dennis03@yahoo.com|      Kimberlyview|   MD|
|     C00010|     James|    Myers|charles58@murillo...|       West Hector|   OK|
|     C00011|     Jacob|       Le|   anita65@gmail.com|       Houstonfurt|   AR|
|     C00012|      Chad|    Banks|beardtravis@gmail...| East Jenniferview|   WI|
|     C00013|     James|   Martin|     jwood@gmail.com| Lake Gregoryshire|   OR|
|     C00014|    Thomas|  Hartman|    lmoore@yahoo.com|  East Tiffanybury|   MS|
|     C00015|     Diane|   Harris|daniellowe@hotmai...|    South Courtney|   SC|
|     C00016|     Brett|   Parker|  amylam@collins.org|        Jesusburgh|   IA|
|     C00017|    Angela|   Carter|rhondaferguson@gm...|  West Loriborough|   GA|
|     C00018|   Darrell|    Chang|martinfrank@brook...|  Lake Joshuamouth|   OH|
|     C00019|     Angie|     King|russelltimothy@si...|  East Anthonyland|   NY|
|     C00020|      Juan|  Collins|rojassandra@hotma...|       South Oscar|   NV|
+-----------+----------+---------+--------------------+------------------+-----+
only showing top 20 rows

In [5]:
df = df.withColumn("domains", split(col("email"), "@")[1])
df.show()

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

+-----------+----------+---------+--------------------+------------------+-----+------------------+
|customer_id|first_name|last_name|               email|              city|state|           domains|
+-----------+----------+---------+--------------------+------------------+-----+------------------+
|     C00001|     Emily|   Mooney|   rushjeff@ryan.org|      Johnsonmouth|   MS|          ryan.org|
|     C00002|    Andrea|  Sellers|mccoykiara@kelly.com|       Stephenfort|   WY|         kelly.com|
|     C00003|     Craig|    Hayes|rebeccamiller@yah...|South Stephenshire|   LA|         yahoo.com|
|     C00004|     Bryan|    Scott|lawrence05@campbe...|         Chrisland|   ND|     campbell.info|
|     C00005|      Sean|  Vasquez|  carrie45@yahoo.com|   East Dennistown|   RI|         yahoo.com|
|     C00006|     Kevin| Mccarthy|traceyramos@gmail...|     North Matthew|   IN|         gmail.com|
|     C00007|    Amanda|    Doyle|scottallen@gmail.com|        Joneshaven|   VA|         gmail.com|
|     C00008|      Paul|   Campos|sullivanjeremy@ho...|  South Nathanfurt|   CT|  horton-adams.com|
|     C00009|      Mary|    Green|  dennis03@yahoo.com|      Kimberlyview|   MD|         yahoo.com|
|     C00010|     James|    Myers|charles58@murillo...|       West Hector|   OK|       murillo.net|
|     C00011|     Jacob|       Le|   anita65@gmail.com|       Houstonfurt|   AR|         gmail.com|
|     C00012|      Chad|    Banks|beardtravis@gmail...| East Jenniferview|   WI|         gmail.com|
|     C00013|     James|   Martin|     jwood@gmail.com| Lake Gregoryshire|   OR|         gmail.com|
|     C00014|    Thomas|  Hartman|    lmoore@yahoo.com|  East Tiffanybury|   MS|         yahoo.com|
|     C00015|     Diane|   Harris|daniellowe@hotmai...|    South Courtney|   SC|       hotmail.com|
|     C00016|     Brett|   Parker|  amylam@collins.org|        Jesusburgh|   IA|       collins.org|
|     C00017|    Angela|   Carter|rhondaferguson@gm...|  West Loriborough|   GA|         gmail.com|
|     C00018|   Darrell|    Chang|martinfrank@brook...|  Lake Joshuamouth|   OH|       brooks.info|
|     C00019|     Angie|     King|russelltimothy@si...|  East Anthonyland|   NY|simpson-hunter.com|
|     C00020|      Juan|  Collins|rojassandra@hotma...|       South Oscar|   NV|       hotmail.com|
+-----------+----------+---------+--------------------+------------------+-----+------------------+
only showing top 20 rows

In [6]:
df2 = df.groupBy("domains").agg(count("customer_id").alias("total_customers"))\
    .sort("total_customers", ascending=False)
df2.show()

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

+-------------+---------------+
|      domains|total_customers|
+-------------+---------------+
|    gmail.com|            374|
|  hotmail.com|            360|
|    yahoo.com|            331|
|    davis.com|              8|
|    brown.com|              8|
|    smith.com|              7|
|hernandez.com|              5|
|  johnson.com|              5|
|  kennedy.com|              4|
|    white.com|              4|
|   miller.com|              4|
| martinez.com|              3|
|    berry.com|              3|
|    allen.com|              3|
|    olson.com|              3|
|    davis.org|              3|
|   brown.info|              3|
|  jackson.com|              3|
|rodriguez.com|              3|
|    perez.com|              3|
+-------------+---------------+
only showing top 20 rows

In [7]:
df_gmail = df.filter(col("domains") == "gmail.com")
df_gmail.show()
time.sleep(5)  # Simulate a delay for demonstration purposes

df_yahoo = df.filter(col("domains") == "yahoo.com")
df_yahoo.show()
time.sleep(5) 

df_hotmail = df.filter(col("domains") == "hotmail.com")
df_hotmail.show()
time.sleep(5)

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

+-----------+----------+----------+--------------------+-----------------+-----+---------+
|customer_id|first_name| last_name|               email|             city|state|  domains|
+-----------+----------+----------+--------------------+-----------------+-----+---------+
|     C00006|     Kevin|  Mccarthy|traceyramos@gmail...|    North Matthew|   IN|gmail.com|
|     C00007|    Amanda|     Doyle|scottallen@gmail.com|       Joneshaven|   VA|gmail.com|
|     C00011|     Jacob|        Le|   anita65@gmail.com|      Houstonfurt|   AR|gmail.com|
|     C00012|      Chad|     Banks|beardtravis@gmail...|East Jenniferview|   WI|gmail.com|
|     C00013|     James|    Martin|     jwood@gmail.com|Lake Gregoryshire|   OR|gmail.com|
|     C00017|    Angela|    Carter|rhondaferguson@gm...| West Loriborough|   GA|gmail.com|
|     C00028|     Barry|     Baker|  steven27@gmail.com|North Gregoryfurt|   NM|gmail.com|
|     C00030|     Holly|   Collins|   cfuller@gmail.com|   Port Coltonton|   AL|gmail.com|
|     C00032|Alexandria| Singleton| egallegos@gmail.com|      Samuelshire|   KS|gmail.com|
|     C00034|     Carol|  Matthews|   stacy78@gmail.com|      Gregorybury|   IA|gmail.com|
|     C00035|  Samantha| Hernandez|   jnorris@gmail.com|       Angelafurt|   MD|gmail.com|
|     C00040| Francisco|     Horne|christianrogers@g...|      New Michael|   TX|gmail.com|
|     C00047|     Wanda|    Morton|  fcalhoun@gmail.com|         Hallview|   OK|gmail.com|
|     C00049|      Mike|    Harvey|kristinawalsh@gma...|  New Heatherside|   IA|gmail.com|
|     C00061|     Brian|   Bullock|marshallwhitney@g...|          Ballton|   DC|gmail.com|
|     C00063|      Tara|      Owen| jessica25@gmail.com|    Robertsonstad|   MS|gmail.com|
|     C00068|    Jerome|   Stevens|  amanda92@gmail.com|North Roberthaven|   ND|gmail.com|
|     C00071|      Jody|Villanueva|feliciasmith@gmai...|    Jenniferburgh|   PA|gmail.com|
|     C00073|   Richard|    Walker|   bryce96@gmail.com|       East Steve|   NM|gmail.com|
|     C00074|   Crystal|   Padilla|   bbarnes@gmail.com|       Susanshire|   TX|gmail.com|
+-----------+----------+----------+--------------------+-----------------+-----+---------+
only showing top 20 rows

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

+-----------+----------+---------+--------------------+------------------+-----+---------+
|customer_id|first_name|last_name|               email|              city|state|  domains|
+-----------+----------+---------+--------------------+------------------+-----+---------+
|     C00003|     Craig|    Hayes|rebeccamiller@yah...|South Stephenshire|   LA|yahoo.com|
|     C00005|      Sean|  Vasquez|  carrie45@yahoo.com|   East Dennistown|   RI|yahoo.com|
|     C00009|      Mary|    Green|  dennis03@yahoo.com|      Kimberlyview|   MD|yahoo.com|
|     C00014|    Thomas|  Hartman|    lmoore@yahoo.com|  East Tiffanybury|   MS|yahoo.com|
|     C00024|   Heather|    Owens|andreawilliams@ya...|       Stewartport|   NM|yahoo.com|
|     C00025| Christina|  Bennett|    dawn65@yahoo.com|    Port Juliebury|   IN|yahoo.com|
|     C00026|      Mark|   Harris| rebecca20@yahoo.com|        Ortizshire|   WY|yahoo.com|
|     C00042|     Jenna|    Lewis|hannasteven@yahoo...|  South Garrettton|   IA|yahoo.com|
|     C00048|   Natalie|   Gentry|floresvanessa@yah...|       Lake Andrea|   MO|yahoo.com|
|     C00051|     Frank| Phillips|millerjennifer@ya...|      Anthonymouth|   CO|yahoo.com|
|     C00058|    Daniel|   Walker|  alexis83@yahoo.com|        Shanehaven|   HI|yahoo.com|
|     C00059|  Michelle|Mcconnell|   raven40@yahoo.com|      Pittschester|   IA|yahoo.com|
|     C00062|   Shelley|  Holland| kimdennis@yahoo.com|      Kaitlynburgh|   MI|yahoo.com|
|     C00075|     Diana|  Andrade|   ngraham@yahoo.com|         Carlytown|   NY|yahoo.com|
|     C00079|      Eric| Gonzalez|simmonsbarbara@ya...|        North Anna|   NC|yahoo.com|
|     C00088| Stephanie|  Pearson|   yorozco@yahoo.com|North Jonathanport|   AZ|yahoo.com|
|     C00089| Christine|   Wright|allisoncalderon@y...|       Mcguireside|   WA|yahoo.com|
|     C00098|    Joseph|    Davis|keithethan@yahoo.com|           Fryberg|   KS|yahoo.com|
|     C00099|   Theresa|    Bruce|jesusspencer@yaho...|       Ashleyville|   KY|yahoo.com|
|     C00101|    Robert|Velasquez|littleanthony@yah...|         Seanmouth|   KY|yahoo.com|
+-----------+----------+---------+--------------------+------------------+-----+---------+
only showing top 20 rows

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

+-----------+----------+---------+--------------------+-------------------+-----+-----------+
|customer_id|first_name|last_name|               email|               city|state|    domains|
+-----------+----------+---------+--------------------+-------------------+-----+-----------+
|     C00015|     Diane|   Harris|daniellowe@hotmai...|     South Courtney|   SC|hotmail.com|
|     C00020|      Juan|  Collins|rojassandra@hotma...|        South Oscar|   NV|hotmail.com|
|     C00031|  Jeanette|    Smith|kramerkaylee@hotm...|         Travisview|   CT|hotmail.com|
|     C00033|    Carrie|  Wheeler|lindasummers@hotm...|South Andrewchester|   CO|hotmail.com|
|     C00036|     Jacob|    Mccoy|jesustaylor@hotma...| Port Nicoleborough|   AR|hotmail.com|
|     C00037|     Holly|   Arnold|  eric78@hotmail.com|         Millerfurt|   VT|hotmail.com|
|     C00038|    Robert|     Haas| ythomas@hotmail.com|   Port Michaelstad|   MS|hotmail.com|
|     C00039|    Teresa|     Ward|angela55@hotmail.com|  Lake Michaelhaven|   AL|hotmail.com|
|     C00041|     James|   Brooks| pbarnes@hotmail.com|       Allisonhaven|   AK|hotmail.com|
|     C00043|  Margaret| Sullivan|ronnie19@hotmail.com|    South Johnville|   OK|hotmail.com|
|     C00045|   Matthew|      Lee|   dkhan@hotmail.com|         North Kara|   OK|hotmail.com|
|     C00046|    Justin|  Collins|josephpatterson@h...|       Barbaramouth|   MO|hotmail.com|
|     C00050|    Mariah|   Wright|franklinalexis@ho...|          Lopezfurt|   CO|hotmail.com|
|     C00052|     Scott|  Mathews| kevin81@hotmail.com|        Chapmanstad|   MS|hotmail.com|
|     C00053|     Kevin|   Harris|zbarnett@hotmail.com|         Jacobville|   AR|hotmail.com|
|     C00055|    Joshua|  Kaufman|  qfoley@hotmail.com|         Bishopview|   NE|hotmail.com|
|     C00056|      Tina|    Cantu|cruzkristen@hotma...|      Catherineberg|   WA|hotmail.com|
|     C00057|    Wesley|    Cohen|nelsonlauren@hotm...|       Petersonside|   SC|hotmail.com|
|     C00064| Francisco|Hernandez|greenamanda@hotma...|       Jenningsberg|   TN|hotmail.com|
|     C00066|     James|   Austin| david75@hotmail.com|       Carrilloside|   WA|hotmail.com|
+-----------+----------+---------+--------------------+-------------------+-----+-----------+
only showing top 20 rows

In [8]:
df_wfn = df.withColumn("full_name", concat(col('first_name'), lit(' '), col('last_name')))\
    .drop("first_name", "last_name")
    
df_wfn.show()

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

+-----------+--------------------+------------------+-----+------------------+--------------+
|customer_id|               email|              city|state|           domains|     full_name|
+-----------+--------------------+------------------+-----+------------------+--------------+
|     C00001|   rushjeff@ryan.org|      Johnsonmouth|   MS|          ryan.org|  Emily Mooney|
|     C00002|mccoykiara@kelly.com|       Stephenfort|   WY|         kelly.com|Andrea Sellers|
|     C00003|rebeccamiller@yah...|South Stephenshire|   LA|         yahoo.com|   Craig Hayes|
|     C00004|lawrence05@campbe...|         Chrisland|   ND|     campbell.info|   Bryan Scott|
|     C00005|  carrie45@yahoo.com|   East Dennistown|   RI|         yahoo.com|  Sean Vasquez|
|     C00006|traceyramos@gmail...|     North Matthew|   IN|         gmail.com|Kevin Mccarthy|
|     C00007|scottallen@gmail.com|        Joneshaven|   VA|         gmail.com|  Amanda Doyle|
|     C00008|sullivanjeremy@ho...|  South Nathanfurt|   CT|  horton-adams.com|   Paul Campos|
|     C00009|  dennis03@yahoo.com|      Kimberlyview|   MD|         yahoo.com|    Mary Green|
|     C00010|charles58@murillo...|       West Hector|   OK|       murillo.net|   James Myers|
|     C00011|   anita65@gmail.com|       Houstonfurt|   AR|         gmail.com|      Jacob Le|
|     C00012|beardtravis@gmail...| East Jenniferview|   WI|         gmail.com|    Chad Banks|
|     C00013|     jwood@gmail.com| Lake Gregoryshire|   OR|         gmail.com|  James Martin|
|     C00014|    lmoore@yahoo.com|  East Tiffanybury|   MS|         yahoo.com|Thomas Hartman|
|     C00015|daniellowe@hotmai...|    South Courtney|   SC|       hotmail.com|  Diane Harris|
|     C00016|  amylam@collins.org|        Jesusburgh|   IA|       collins.org|  Brett Parker|
|     C00017|rhondaferguson@gm...|  West Loriborough|   GA|         gmail.com| Angela Carter|
|     C00018|martinfrank@brook...|  Lake Joshuamouth|   OH|       brooks.info| Darrell Chang|
|     C00019|russelltimothy@si...|  East Anthonyland|   NY|simpson-hunter.com|    Angie King|
|     C00020|rojassandra@hotma...|       South Oscar|   NV|       hotmail.com|  Juan Collins|
+-----------+--------------------+------------------+-----+------------------+--------------+
only showing top 20 rows

In [9]:
df_wfn.write.format("delta")\
    .mode("overwrite")\
    .save("s3://learn-databricks-project-e2e-1-silver/customers")

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

In [10]:
%sql

CREATE SCHEMA IF NOT EXISTS learn_e2e_1.silver

DataFrame[]

In [13]:
%sql

CREATE TABLE IF NOT EXISTS learn_e2e_1.silver.customers
USING DELTA
LOCATION 's3://learn-databricks-project-e2e-1-silver/customers'

DataFrame[]