In [1]:
dbutils.widgets.text("init_load_flag", "True")

Box(children=(Label(value='init_load_flag'), Text(value='True')))

In [2]:
init_load_flag = bool(dbutils.widgets.get("init_load_flag"))
init_load_flag

True

In [3]:
from pyspark.sql.functions import *
from pyspark.sql.types import *

# Data Reading from Source

In [4]:
df = spark.sql(
    """
    SELECT * FROM learn_e2e_1.silver.customers
    """
)
df

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

DataFrame[customer_id: string, email: string, city: string, state: string, domains: string, full_name: string]

Removing Duplicates

In [5]:
df = df.dropDuplicates(subset=["customer_id"])
df

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

DataFrame[customer_id: string, email: string, city: string, state: string, domains: string, full_name: string]

** Surrogate Key - All The Values **

In [6]:
df = df.withColumn("DimCustomerKey", monotonically_increasing_id()+lit(1))
df

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

DataFrame[customer_id: string, email: string, city: string, state: string, domains: string, full_name: string, DimCustomerKey: bigint]

## Dividing New vs Old Records

In [7]:
if init_load_flag == False:
    df_old = spark.sql(
        """
            SELECT DimCustomerKey, customer_id, create_date, update_date
            FROM learn_e2e_1.gold.customers
        """)

else:
    df_old = spark.sql(
        """
            SELECT 0 DimCustomerKey, 0 customer_id, 0 create_date, 0 update_date 
            FROM learn_e2e_1.silver.customers
            WHERE 1=0
        """)
    
df_old

DataFrame[DimCustomerKey: int, customer_id: int, create_date: int, update_date: int]

#### Renaming Columns of df_old

In [8]:
df_old = df_old.withColumnRenamed("DimCustomerKey", "old_DimCustomerKey") \
    .withColumnRenamed("customer_id", "old_customer_id") \
    .withColumnRenamed("create_date", "old_create_date") \
    .withColumnRenamed("update_date", "old_update_date")
df_old

DataFrame[old_DimCustomerKey: int, old_customer_id: int, old_create_date: int, old_update_date: int]

#### Applying Join with Old Records

In [9]:
df_join = df.join(df_old, df['customer_id'] == df_old['old_customer_id'], "left")
df_join

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

DataFrame[customer_id: string, email: string, city: string, state: string, domains: string, full_name: string, DimCustomerKey: bigint, old_DimCustomerKey: int, old_customer_id: int, old_create_date: int, old_update_date: int]

#### Separating New vs Old Records

In [10]:
df_new = df_join.filter(df_join['old_DimCustomerKey'].isNull())
df_new

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

DataFrame[customer_id: string, email: string, city: string, state: string, domains: string, full_name: string, DimCustomerKey: bigint, old_DimCustomerKey: int, old_customer_id: int, old_create_date: int, old_update_date: int]

In [11]:
df_update = df_join.filter(df_join['old_DimCustomerKey'].isNotNull())
df_update

DataFrame[customer_id: string, email: string, city: string, state: string, domains: string, full_name: string, DimCustomerKey: bigint, old_DimCustomerKey: int, old_customer_id: int, old_create_date: int, old_update_date: int]

#### Preparing df_old

In [12]:
# Droppping all the columns which are not required
df_update = df_update.drop('old_DimCustomerKey', 'old_customer_id', 'old_update_date')

# Renaming "old_create_date" to "create_date"
df_update = df_update.withColumnRenamed("old_create_date", "create_date")
df_update = df_update.withColumn("create_date", to_timestamp(col("create_date")))

# Recreating "update_date" column
df_update = df_update.withColumn("update_date", current_timestamp())
df_update

DataFrame[customer_id: string, email: string, city: string, state: string, domains: string, full_name: string, DimCustomerKey: bigint, create_date: timestamp, update_date: timestamp]

#### Preparing df_new

In [13]:
# Dropping all the columns which are not required
df_new = df_new.drop("old_DimCustomerKey", "old_customer_id", "old_create_date", "old_update_date")

#Recreating "create_date" and "update_date" columns
df_new = df_new.withColumn("create_date", current_timestamp()) \
    .withColumn("update_date", current_timestamp())
    
df_new

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

DataFrame[customer_id: string, email: string, city: string, state: string, domains: string, full_name: string, DimCustomerKey: bigint, create_date: timestamp, update_date: timestamp]

#### Surrogate Key - From 1

In [14]:
df_new = df_new.withColumn("DimCustomerKey", monotonically_increasing_id() + lit(1))
df_new

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

DataFrame[customer_id: string, email: string, city: string, state: string, domains: string, full_name: string, DimCustomerKey: bigint, create_date: timestamp, update_date: timestamp]

#### Adding Max Surrogate Key

In [15]:
if init_load_flag == True:
    max_surrogate_key = 0
else:
    df_maxsur = spark.sql(
        """
            SELECT max(DimCustomerKey) AS max_surrogate_key
            FROM learn_e2e_1.gold.customers
        """
    )
    
    #### Converting df_maxsur to max_surrogate_key variable
    max_surrogate_key = df_maxsur.collect()[0]['max_surrogate_key']
    
max_surrogate_key

df_new

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

DataFrame[customer_id: string, email: string, city: string, state: string, domains: string, full_name: string, DimCustomerKey: bigint, create_date: timestamp, update_date: timestamp]

In [16]:
df_new = df_new.withColumn("DimCustomerKey",lit(max_surrogate_key) + col("DimCustomerKey"))

#### Union of df_old and df_new

In [17]:
df_final = df_new.unionByName(df_update)
df_final

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

DataFrame[customer_id: string, email: string, city: string, state: string, domains: string, full_name: string, DimCustomerKey: bigint, create_date: timestamp, update_date: timestamp]

#### SCD Type - 1

In [18]:
from delta.tables import DeltaTable

In [20]:
if spark.catalog.tableExists("learn_e2e_1.gold.customers"):
    dlt_object = DeltaTable.forPath(spark, "s3://learn-databricks-project-e2e-1-gold/dimCustomers") 
    
    dlt_object.alias("tgt").merge(df_final.alias("src"), "tgt.DimCustomerKey = src.DimCustomerKey") \
        .whenMatchedUpdateAll() \
        .whenNotMatchedInsertAll() \
        .execute()

else:
    df_final.write.mode("overwrite") \
        .format("delta") \
        .option("path", "s3://learn-databricks-project-e2e-1-gold/dimCustomers") \
        .saveAsTable("learn_e2e_1.gold.customers")

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))